services:
  # Backend Node.js API Server
  - type: web
    name: thenextera-backend
    env: node
    rootDir: ./Server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: ATLASDB_URL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false

  # Frontend Static Site
  - type: web
    name: thenextera-frontend
    env: static
    rootDir: ./Client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
